---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
The human heart has hidden treasures,   
In secret kept, in silence sealed;    
The thoughts, the hopes, the dreams, the pleasures,   
Whose charms were broken if revealed.   
And days may pass in gay confusion,   
And nights in rosy riot fly,   
While, lost in Fame's or Wealth's illusion,     
The memory of the Past may die.   

But, there are hours of lonely musing,   
Such as in evening silence come,   
When, soft as birds their pinions closing,   
The heart's best feelings gather home.   
Then in our souls there seems to languish   
A tender grief that is not woe;   
And thoughts that once wrung groans of anguish,   
Now cause but some mild tears to flow.   